[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_source = "let g:deoplete#enable_at_startup = 1"
on_i = 1

[[plugins]]
repo = "OmniSharp/omnisharp-vim"
on_ft = ["cs"]
build = "xbuild server/OmniSharp.sln"

[[plugins]]
repo = "Robzz/deoplete-omnisharp"
on_source = ["deoplete.nvim"]
